name: airshift
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  google_mlkit_pose_detection: ^0.10.0
  nsd: ^4.0.0
  flutter_blue_plus: ^1.31.0
  flutter_local_notifications: ^17.0.0
  sensors_plus: ^5.0.0
  permission_handler: ^11.0.0
  path_provider: ^2.1.0
  screenshot: ^3.0.0
  path: ^1.9.0
  crypto: ^3.0.3
  uuid: ^4.0.0
  lottie: ^3.0.0
  hotkey_manager: ^0.2.3
  camera: ^0.12.0+1
  camera_windows: ^0.2.6+4
  google_mlkit_commons: ^0.6.1
  flutter_overlay_window: ^0.5.0
  window_manager: ^0.5.1
  flutter_acrylic: ^1.1.4
  receive_sharing_intent: ^1.8.1
  basic_utils: ^5.8.2
  pointycastle: ^4.0.0
  webview_windows: ^0.2.2
  video_player: ^2.11.1
  quick_settings: ^1.0.1
  shared_preferences: ^2.5.5
  win32: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/web/
